services:
  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URL=postgresql://postgres:p0Stpw14@db:5432/evaluation_db
      - FLASK_APP=app.py
      - FLASK_ENV=development
    depends_on:
      - db

  db:
    image: postgres:14
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: p0Stpw14
      POSTGRES_DB: evaluation_db
    volumes:
      - gathered_data:/var/lib/postgresql/data

volumes:
  gathered_data: