services:
  web:
    build: .
    ports:
      - "80:80"
    environment:
      - DATABASE_URL=postgresql://postgres:p0Stpw14@db:5432/evaluation_db
    depends_on:
      - db

  db:
    image: postgres:14
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: p0Stpw14
      POSTGRES_DB: evaluation_db
    volumes:
      - ./data:/var/lib/postgresql/data

volumes:
  data: {}